version: "3.5"

services:
  api01: &api
    image: api-rinha:snapshot
    build:
      dockerfile: Dockerfile
      context: ../
    hostname: api01
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    volumes:
      - ../app:/code/app
    environment:
      - DB_USER=admin
      - DB_PASSWORD=123
      - DB_NAME=rinha
      - DB_HOST=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"

  api02:
    <<: *api
    hostname: api02
    
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  db:
    image: postgres:latest
    hostname: db
    command: ['postgres', '-c', 'max_connections=100', '-c', 'work_mem=4MB', '-c', 'maintenance_work_mem=16MB', '-c', 'effective_cache_size=128MB', '-c', 'checkpoint_completion_target=0.5', '-c', 'shared_buffers=64MB', '-c', 'synchronous_commit=off', '-c', 'fsync=off', '-c', 'full_page_writes=off', '-c', 'checkpoint_timeout=600', '-c', 'max_wal_size=4096']
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "240MB"

  adminer:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=matheuswcf@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=julianalao
    ports:
      - "9000:80"
    depends_on:
      - db

networks:
  default:
    driver: bridge
